language: ruby

sudo: required

notifications:
  slack: watzekdi:3ePbwCVsfxG4hrbo0dtBLa0r

branches:
  only:
    - master

services:
  - postgresql

rvm:
    - 2.3.1

cache: bundler

bundler_args: --without production

before_install:
  - gem install bundler
  - gem update --system
  - bundle update rake

script:
  - rake db:create
  - rake db:test:prepare
  - rake test
